services:
  # Main Web Service (FastAPI backend)
  - type: web
    name: copilot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: copilot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: copilot-redis
          type: redis
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  # Celery Worker
  - type: worker
    name: copilot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker worker --loglevel=info
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: copilot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: copilot-redis
          type: redis
          property: connectionString
    plan: starter

  # Vector Database - Milvus via Docker
  - type: pserv
    name: copilot-milvus
    env: docker
    dockerfilePath: ./milvus-docker/Dockerfile
    plan: standard

  # Redis instance
  - type: redis
    name: copilot-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter

databases:
  # PostgreSQL Database
  - name: copilot-db
    plan: starter 