services:
  # Main Web Service (FastAPI backend)
  - type: web
    name: copilot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: copilot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: copilot-redis
          type: redis
          property: connectionString
    plan: standard # Need at least standard for WebSockets

  # Celery Worker
  - type: worker
    name: copilot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker worker --loglevel=info
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: copilot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: copilot-redis
          type: redis
          property: connectionString
    plan: starter

  # Vector Database - Milvus via Docker
  - type: pserv
    name: copilot-milvus
    env: docker
    dockerfilePath: ./milvus-docker/Dockerfile
    plan: standard

  # Redis instance
  - type: redis
    name: copilot-redis
    ipAllowList: # optional
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter

databases:
  # PostgreSQL Database
  - name: copilot-db
    plan: starter 